version: '3'
services:
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: lang_production
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        networks:
            - mynet

    web:
        build: .
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        environment:
            RAILS_ENV: production
        ports:
            - "3000:3000"
        links:
            - db
        networks:
            - mynet
networks:
    mynet:
        external: true
